spring:
  application:
    name: heurislink

  datasource:
    url: jdbc:postgresql://localhost:5432/heurislink
    username: postgres
    password: postgres

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

server:
  port: 8080

app:
  base-url: http://localhost:8080