spring:
  application:
    name: heurislink

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/heurislink}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cache:
    type: redis
    cache-names: shortUrls
    redis:
      time-to-live: 10m

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

    consumer:
      group-id: heurislink-click-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer

      properties:
        spring.json.trusted.packages: com.batuhan.heurislink.event

server:
  port: 8080

app:
  base-url: ${APP_BASE_URL:http://localhost:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.flywaydb: DEBUG