apiVersion: apps/v1
kind: Deployment
metadata:
  name: heurislink
  namespace: heurislink

spec:

  progressDeadlineSeconds: 300

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: heurislink

  template:
    metadata:
      labels:
        app: heurislink

    spec:
      terminationGracePeriodSeconds: 40

      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault

      imagePullSecrets:
        - name: ghcr-pull-secret

      containers:
        - name: heurislink
          image: ghcr.io/batuhanacar/heurislink:latest
          imagePullPolicy: Always

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          envFrom:
            - configMapRef:
                name: heurislink-config

          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: heurislink-db-secret
                  key: username

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: heurislink-db-secret
                  key: password

          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 36

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 768Mi
              cpu: 500m

          volumeMounts:
            - name: tmp
              mountPath: /tmp

      volumes:
        - name: tmp
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: heurislink
  namespace: heurislink

spec:
  type: ClusterIP

  selector:
    app: heurislink

  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP